cryostatio/jfr-datasource

- README.md
https://github.com/rh-jmc-team/jfr-datasource/issues/13
> Update readme. Fix instructions and add API

- README.md
- docker/builder/Dockerfile
- docker/builder/s2i/assemble
- docker/builder/s2i/assemble-runtime
- docker/runtime/Dockerfile
- docker/runtime/s2i/assemble-runtime
- docker/runtime/s2i/run
Addresses https://github.com/rh-jmc-team/jfr-datasource/issues/7
> Add support for s2i runtime image

- README.md
Addresses https://github.com/rh-jmc-team/jfr-datasource/issues/20
> Fix readme repository references

- server/src/main/java/com/redhat/jfr/events/RecordingService.java
Addresses https://github.com/rh-jmc-team/jfr-datasource/issues/29
> Exclude certain event attributes

- server/src/main/java/com/redhat/jfr/events/RecordingService.java
Fixes https://github.com/rh-jmc-team/jfr-datasource/issues/31
> Skip events that don't contain '.'

- dashboards/dashboard.json
Addresses https://github.com/rh-jmc-team/jfr-datasource/issues/25
> Add Grafana dashboard json file

- setup/SETUP.md
> Add oc instructions

- pom.xml
- server/pom.xml
- server/src/test/java/com/redhat/jfr/tests/DatasourceTest.java
- server/src/test/java/com/redhat/jfr/tests/NativeDatasourceIT.java
Adds infrastructure for testing of http endpoints and a basic test of `/`
Addresses https://github.com/rh-jmc-team/jfr-datasource/issues/10
> Add http request tests

- README.md
- server/src/main/java/com/redhat/jfr/server/JfrResource.java
> Upload files with original name. Update README

- server/src/main/java/com/redhat/jfr/server/JfrResource.java
- server/src/test/java/com/redhat/jfr/tests/DatasourceTest.java
Addresses https://github.com/rh-jmc-team/jfr-datasource/issues/35
Also fixes indentation of JfrResource file
> Fix list endpoint when upload directory is empty or doesn't exist

- README.md
- pom.xml
- releng/dep-check-suppressions.xml
Backport of #55. Only change is keeping the project version at 1.0.0-SNAPSHOT.
> [v1] Check for vulnerable deps, misc cleanup

- pom.xml
> [v1] Attach runner jar to build with build-helper-maven-plugin

- README.md
- pom.xml
- src/main/java/com/redhat/jfr/server/JfrResource.java
- src/main/resources/application.properties
- src/test/java/com/redhat/jfr/tests/DatasourceTest.java
> Update to Quarkus 1.11.6

- README.md
- pom.xml
> [v1] Use AdoptOpenJDK Maven repo for JMC core

- pom.xml
- src/main/java/io/cryostat/jfr/datasource/events/RecordingService.java
- src/main/java/io/cryostat/jfr/datasource/json/JsonUtils.java
- src/main/java/io/cryostat/jfr/datasource/server/JfrResource.java
- src/main/java/io/cryostat/jfr/datasource/server/Query.java
- src/main/java/io/cryostat/jfr/datasource/server/Target.java
- src/main/java/io/cryostat/jfr/datasource/utils/ArgRunnable.java
- src/test/java/io/cryostat/jfr/datasource/tests/DatasourceTest.java
- src/test/java/io/cryostat/jfr/datasource/tests/NativeDatasourceIT.java
> [v1] Rename to match Cryostat project

- pom.xml
> build(version): bump version to 2.1.0-SNAPSHOT

- README.md
- src/main/resources/application.properties
> fix(application.properties): increase default http max-body-size

- .github/workflows/ci.yaml
- .mergify.yml
> build(ci): run CI on v2 and add backport bot config

- pom.xml
> build(version): bump version to 2.2.0-SNAPSHOT

- pom.xml
> build(version): set version for 2.1.0 release

- pom.xml
> build(version): bump version to 2.1.1-SNAPSHOT

- pom.xml
- src/main/java/io/cryostat/jfr/datasource/events/RecordingService.java
- src/main/java/io/cryostat/jfr/datasource/json/JsonUtils.java
- src/main/java/io/cryostat/jfr/datasource/server/JfrResource.java
- src/main/java/io/cryostat/jfr/datasource/server/Query.java
- src/main/java/io/cryostat/jfr/datasource/server/Target.java
- src/main/java/io/cryostat/jfr/datasource/utils/ArgRunnable.java
- src/test/java/io/cryostat/jfr/datasource/tests/DatasourceTest.java
- src/test/java/io/cryostat/jfr/datasource/tests/NativeDatasourceIT.java
Fixes #105 
Add spotless plugin for code formatting.
> chore(mvn): add spotless plugin for code formatting

- README.md
> chore(readme): update version of native artifact

- .github/workflows/ci.yaml
- .mvn/jvm.config
- README.md
- pom.xml
Fixes #103
`.mvn/jvm.config` required for same reason as in https://github.com/cryostatio/cryostat-core/pull/146
> chore(pom): update to JDK17

- pom.xml
> build(deps): use rest-assured from quarkus-bom

- README.md
- src/main/java/io/cryostat/jfr/datasource/server/JfrResource.java
- src/test/java/io/cryostat/jfr/datasource/server/DatasourceTest.java
Fixes #34 
Thoughts? My knowledge on how to maintain async state in Java could be better so I'm wondering how this problem should be approached, seems like there are several ways this could've been done. Also might not be very robust.
> feat(console): currently selected file now shown

- src/main/docker/Dockerfile.native
> fix(image): specify a user ID in the Dockerfile

- pom.xml
- src/assembly/native-sources.xml
> build(native): add native-sources profile

- src/main/docker/Dockerfile.native
Related to cryostatio/cryostat#1118
> build(baseimage): use 8.6 tagged base image

- .github/workflows/pr-ci.yaml
- .github/workflows/push-ci.yaml
- pom.xml
Related to cryostatio/cryostat#1118
Fixes #116
> ci(push): add config for CI build and publish on push

- .github/workflows/push-ci.yaml
Related to #147
Should fix job failure: https://github.com/cryostatio/jfr-datasource/pull/148#issuecomment-1315831378
> ci(push): fix container stream name

- pom.xml
Related to cryostatio/cryostat#1118
Depends on #147
> chore(pom): set version to 2.2.0

- pom.xml
Related to cryostatio/cryostat#1118
> chore(pom): set version to 2.2.1-SNAPSHOT

- .mergify.yml
- pom.xml
Related to https://github.com/cryostatio/cryostat/issues/1459
> build(config): update pom and mergify for 2.3 release 

- src/main/docker/Dockerfile.jvm
Fixes #212 
See also https://github.com/cryostatio/cryostat-reports/pull/136
> fix(dockerfile): use JAVA_OPTS_APPEND and do not ExitOnOutOfMemoryError

- src/main/java/io/cryostat/jfr/datasource/server/Datasource.java
> feat(uploads): Evaluate incoming JFR files for processing

- pom.xml
> build(deps): upgrade Netty to 4.1.100.Final

- src/main/java/io/cryostat/jfr/datasource/events/RecordingService.java
- src/main/java/io/cryostat/jfr/datasource/server/Datasource.java
> fix(logs): fix format specifiers in Log messages

- pom.xml
> build(pom): correct release branch project version

- pom.xml
> build(pom): remove unused repository

- .github/dependabot.yml
Related to: https://github.com/cryostatio/cryostat3/issues/363
> chore(deps): ignore major/minor Quarkus updates

- pom.xml
See https://github.com/cryostatio/cryostat-reports/pull/234
> chore(pom): bump version to 3.0.0-SNAPSHOT

- pom.xml
Related to https://github.com/cryostatio/cryostat/issues/364
> build(deps): update to Quarkus 3.8 LTS

- src/main/docker/Dockerfile.jvm
Based on https://github.com/cryostatio/jfr-datasource/pull/326
Depends on https://github.com/cryostatio/jfr-datasource/pull/326
Related to https://github.com/cryostatio/cryostat/issues/650
> chore(container): upgrade to UBI9

- pom.xml
See https://github.com/cryostatio/cryostat/pull/936
> chore(quarkus): upgrade to Quarkus 3.20 LTS

- src/main/docker/Dockerfile.jvm
> build(deps): correct base image tag
