- README.md
- server/src/main/java/com/redhat/jfr/server/JfrResource.java
This removes the jfrDir configuration in favour of a static directory 'file-uploads'. In the future configuration can be added back, but in a fully functional state rather than a partially functional state.
> Remove jfrDir configuration

- docker/builder/Dockerfile
`centos-quarkus-native-s2i` is replaced by `ubi-quarkus-native-s2i` which has a newer version of graalvm, needed for the updated plugins used by the project.
> Update base image for s2i builder

- pom.xml
- src/main/docker/Dockerfile.native
This will allow us to optionally listen for only connections from containers in the same pod by setting LISTEN_HOST to 127.0.0.1. I have also updated to a more recent version of Quarkus.
> Make listen host configurable, bump Quarkus version

- README.md
- pom.xml
- releng/dep-check-suppressions.xml
This PR adds a profile to check for vulnerable dependencies using OWASP Dependency Check. There's a suppression file added for false positives related to smallrye-mutiny. This also upgrades Quarkus to pull in a newer vertx which fixes CVE-2019-17640, and JMC to 7.1.0-SNAPSHOT to closer align with what's used for Container JFR.
I also bumped the version to 2.0.0 (will backport to v1 branch) and fixed up the README a bit.
> Check for vulnerable deps, misc cleanup

- pom.xml
The versions for the Quarkus dependencies we use are already defined within the quarkus-bom we import. This eliminates the redundant version tags in our POM. This also helps with downstream builds.
> Use Quarkus versions defined in BOM

- pom.xml
Direct backport of #57. No conflicts.
> [v1] Use Quarkus versions defined in BOM

- pom.xml
This PR attaches the runner jar produced by quarkus-maven-plugin to the build's artifacts. This includes the runner jar when installing/deploying artifacts to a Maven repository.
> Attach runner jar to build with build-helper-maven-plugin

- README.md
- pom.xml
- src/main/java/com/redhat/jfr/server/JfrResource.java
- src/main/resources/application.properties
- src/test/java/com/redhat/jfr/tests/DatasourceTest.java
This PR updates Quarkus, and changes the build to match the current recommendations:
https://quarkus.io/version/1.11/guides/maven-tooling
Additionally, the uploads directory is read from Quarkus's configuration, instead of relying on the default location. This is useful as the default directory is changing in 1.12:
https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.12#http
I also updated the README native-image build instructions to be more reproducible. An image for testing is available at `quay.io/ebaron/jfr-datasource:1.0.0-BETA6`.
> Update to Quarkus 1.11.6

- README.md
- pom.xml
Similar to https://github.com/cryostatio/cryostat-core/pull/80, we can use the AdoptOpenJDK Maven repo for released JMC core artifacts.
> Use AdoptOpenJDK Maven repo for JMC core

- pom.xml
- src/main/java/io/cryostat/jfr/datasource/events/RecordingService.java
- src/main/java/io/cryostat/jfr/datasource/json/JsonUtils.java
- src/main/java/io/cryostat/jfr/datasource/server/JfrResource.java
- src/main/java/io/cryostat/jfr/datasource/server/Query.java
- src/main/java/io/cryostat/jfr/datasource/server/Target.java
- src/main/java/io/cryostat/jfr/datasource/utils/ArgRunnable.java
- src/test/java/io/cryostat/jfr/datasource/tests/DatasourceTest.java
- src/test/java/io/cryostat/jfr/datasource/tests/NativeDatasourceIT.java
This simply renames the Maven group ID and package names to better match the Cryostat project. Some imports are cleaned up as well.
> Rename to match Cryostat project

- .github/workflows/ci.yaml
This should resolve a problem with CI adding a `-javaagent` argument to `MAVEN_OPTS` that Quarkus doesn't recognize:
https://github.com/quarkusio/quarkus/issues/16862
> Use actions/cache for CI builds

- README.md
- src/main/resources/application.properties
Clean backport of #84 to v2
* fix(application.properties): increase default http max-body-size
* Document webserver HTTP body size limit
> fix(application.properties): increase default http max-body-size

- src/main/java/io/cryostat/jfr/datasource/server/JfrResource.java
Fixes #88 
Fixes main thread being blocked when performing long IO operations in routes: `/set`, `/upload`, `/load`.
> Fix(jfr): Fix IO operation blocking main thread

- src/test/java/io/cryostat/jfr/datasource/server/NativeDatasourceIT.java
Fixes #110 
Current solution is to have a separate test implementation for native image tests. Now, it is just a copy from unit test but removing mocking.
> test(native): fix native-image fail since not supporting injected bean

- src/main/java/io/cryostat/jfr/datasource/server/JfrResource.java
- src/test/java/io/cryostat/jfr/datasource/server/DatasourceTest.java
- src/test/java/io/cryostat/jfr/datasource/server/NativeDatasourceIT.java
Fixes #123 
Related to #122 
Correct headers for endpoints since some do not return JSON-formatted response but still set `application/json` header.
Added tests for `/current` endpoint to native image while cleaning up tests.
I also enforce allowed VERB for each endpoints.
> fix(headers): correct headers for endpoints

- LICENSE
- pom.xml
- src/main/java/io/cryostat/jfr/datasource/events/RecordingService.java
- src/main/java/io/cryostat/jfr/datasource/json/JsonUtils.java
- src/main/java/io/cryostat/jfr/datasource/server/JfrResource.java
- src/main/java/io/cryostat/jfr/datasource/server/Query.java
- src/main/java/io/cryostat/jfr/datasource/server/Target.java
- src/main/java/io/cryostat/jfr/datasource/sys/FileSystemService.java
- src/main/java/io/cryostat/jfr/datasource/utils/ArgRunnable.java
- src/test/java/io/cryostat/jfr/datasource/server/DatasourceTest.java
- src/test/java/io/cryostat/jfr/datasource/server/NativeDatasourceIT.java
Fixes #131
Updated license to UPL as other projects.
Added `license-maven-plugin` to check license headers.
> fix(license): update project license

- README.md
- src/main/java/io/cryostat/jfr/datasource/server/Datasource.java
- src/test/java/io/cryostat/jfr/datasource/server/DatasourceTest.java
- src/test/java/io/cryostat/jfr/datasource/server/NativeDatasourceIT.java
Fixes #152 
Route `/upload` and `load` now allows setting query parameter `?overwrite=true`, which will overwrite any existing files of the same name.
Tests need a bit adjusting since if `/load` route is tested first, selected files will have the form `**file-name**`.
> feat(uploads): allow overwrite existing jfr files

- .github/workflows/push-ci.yaml
- README.md
- pom.xml
- src/main/java/io/cryostat/jfr/datasource/server/Datasource.java
- src/test/java/io/cryostat/jfr/datasource/server/NativeDatasourceIT.java
Fixes #164 
Migrate Quarkus to 2.13 ([2.13.7.Final](https://mvnrepository.com/artifact/io.quarkus/quarkus-bom/2.13.7.Final)). 
References:
- https://github.com/quarkusio/quarkus/wiki/Migration-Guides
- https://access.redhat.com/articles/4966181#RHBQ_2_13_x
> build(quarkus): migrate to quarkus 2.13

- .github/workflows/pr-ci.yaml
Related to https://github.com/cryostatio/cryostat/issues/1401
See https://github.com/actions/setup-java#supported-distributions
Update ci to use `temurin` jdk.
> chore(ci): use temurin distribution jdk

- src/test/java/io/cryostat/jfr/datasource/server/NativeDatasourceIT.java
#160 included calling `trim()` on the expected `/search` output so the file could end with a newline. This needed to be done in NativeDatasourceIT as well. 
Fixes: #185
> test(native): trim newline from expected output

- .github/workflows/push-ci.yaml
- README.md
- pom.xml
- src/main/java/io/cryostat/jfr/datasource/events/RecordingService.java
- src/main/java/io/cryostat/jfr/datasource/server/Datasource.java
- src/main/java/io/cryostat/jfr/datasource/sys/FileSystemService.java
- src/test/java/io/cryostat/jfr/datasource/server/DatasourceTest.java
Fixes #198
Upgrades Quarkus version and native-mode Mandrel builder image version. This was done with the `quarkus update` CLI tool to update the `pom.xml` and do some openrewrite substitutions for changed imports, then manually adjusting tests, README, ci YAML.
`DatasourceTest` is greatly simplified since the vast majority of the mock cases were just proxying the real method calls, so I replaced the mock with a spy and only override the cases where exception handling is tested and a specific override must be made.
Using the usual Cryostat `smoketest.sh`, this can be tested by checking out locally, building a container image, then doing `PULL_IMAGES=missing DATASOURCE_IMAGE=quay.io/cryostat/jfr-datasource:latest sh smoketest.sh`.
> chore(quarkus): upgrade to Quarkus 3

- .github/workflows/pr-ci.yaml
- .github/workflows/push-ci.yaml
Depends on #203
Sample run: https://github.com/andrewazores/jfr-datasource/actions/runs/5892003031/job/15980347125
https://quay.io/repository/andrewazores/jfr-datasource?tab=tags
Related to https://github.com/cryostatio/cryostat/issues/1329
> ci(multiarch): build multiarch JVM mode OCI manifest on push

- pom.xml
- src/assembly/quarkus-app.xml
Adds a `quarkus-app` profile that creates a tarball of the quarkus-app directory. This tarball can be used as input to a separate container image build.
Fixes: #207
> build(assembly): add profile to archive Quarkus artifacts

- src/main/java/io/cryostat/jfr/datasource/events/RecordingService.java
This PR addresses issue 182 [[0]](https://github.com/cryostatio/jfr-datasource/issues/182), in which there are deprecated JMC methods being used: `IType.getAttributes()` and `ItemToolkit.acessor()`.
The approach here is similar to what is found in the jmc core flightrecorder.serializers `IItemCollectionJsonSerializer` [[1]](https://github.com/openjdk/jmc/blob/master/core/org.openjdk.jmc.flightrecorder.serializers/src/main/java/org/openjdk/jmc/flightrecorder/serializers/json/IItemCollectionJsonSerializer.java#L160), where the attributes are instead collected using the `accessorKeys()` on the `IType`. The accessor is then retrieved using the `IType.getAccessor()` instead of using the `ItemToolkit`.
[0] https://github.com/cryostatio/jfr-datasource/issues/182
[1] …
> chore(events): replace deprecated getAttributes method

- pom.xml
This PR updates the JMC core version to 9.0.0, fetching dependencies from Adoptium.
As mentioned in the similar PR to Cryostat3, we'll wait for the corresponding PR to go into cryostat-reports first, and then make sure the CI builds as expected. See: https://github.com/cryostatio/cryostat3/pull/427#pullrequestreview-2034346275
> chore(jmc-core): update to JMC version 9.0.0

- pom.xml
- **build(deps): update to Quarkus 3.8 LTS (#316)**
- **build(deps): bump io.quarkus:quarkus-bom from 3.8.5 to 3.8.6 (#322)**
Related to https://github.com/cryostatio/cryostat/issues/688
> chore(quarkus): upgrade to 3.8 LTS
